### ISSUE TITLE
not defined function

### ISSUE THREAD

**Issue by wcomicho** [wisdomekpotu/react18-firebasev9-auth#2]
Hi,

Tried following your blog: Authentication in React 18 using Firebase v9.

I ran "npm start" but am getting the error below:

ERROR in src\components\Login.js
  Line 29:13:  'googleSignIn' is not defined  no-undef

Hope you can check on this.

Thanks
Wil

**Comment by wisdomekpotu** [comment]
hi thanks for reaching out.  

This error is strange because **googleSignIn** is Defined in src/context/userAuthContext.js 

which is  brought in using the  method  **useUserAuth** into the Login file

Plz at what point in the tutorial did you encounter this error......i will like more info

**Comment by wisdomekpotu** [comment]
okay i see where the error might be coming from.

Just Bring it in. i guess i didnt state it in the tutorial
 ``` const { logIn, googleSignIn } = useUserAuth();```

**Comment by wcomicho** [comment]
> okay i see where the error might be coming from.
> 
> Just Bring it in. i guess i didnt state it in the tutorial ` const { logIn, googleSignIn } = useUserAuth();`
 
Got it. Included it in the code now. 

I am now getting error below:
ERROR in ./src/context/UserAuthContext.js 9:0-35
Module not found: Error: Can't resolve '../firebase' 

Compiled with problems:

ERROR in ./src/context/UserAuthContext.js 9:0-35

Module not found: Error: Can't resolve '../firebase' in 'C:\playground\react18-firebasev9-auth\src\context'

**Comment by karolkocemba** [comment]
> Got it. Included it in the code now.
> 
> I am now getting error below: ERROR in ./src/context/UserAuthContext.js 9:0-35 Module not found: Error: Can't resolve '../firebase'
> 
> Compiled with problems:
> 
> ERROR in ./src/context/UserAuthContext.js 9:0-35
> 
> Module not found: Error: Can't resolve '../firebase' in 'C:\playground\react18-firebasev9-auth\src\context'

@wcomicho  I believe there's a typo in the import. Importing auth from root is not valid in firebase v9, but I believe the author is referencing the "auth" variable defined in line 15 of firebase-config.js

Changing the UserAuthContext.js import to `import { auth } from "../firebase-config";` might be what you are looking for.

**Comment by karolkocemba** [comment]
Take my advice with some skepticism since I'm a python dev just dipping my toes into react + firebase, but this is what I had to do after the change above (in case you are stuck on the google signin):

- In `UserAuthContextProvider.js`, add these imports: 
`import {signInWithPopup, GoogleAuthProvider } from "firebase/auth";`
-create a new function under the `UserAuthContextProvider` function
`function googleSignIn() {
    const googleProvider = new GoogleAuthProvider();
    return signInWithPopup(auth, googleProvider);
  }`
- add this new function to the return statement:
`<userAuthContext.Provider value={{ user, logIn, signUp, logOut, googleSignIn }} >`

Nothing extra seems to be needed to "sign UP" with google, initial login through google from a new user creates a user account automatically visible in the firebase console. 

these docs were helpful: [https://firebase.google.com/docs/auth/web/google-signin#before_you_begin]

Good luck :) 

and thank you @wisdomekpotu for the initial post. Incredibly helpful.

**Comment by wcomicho** [comment]
@karolkocemba 

Got it. Tried and its working now.

Appreciate your help on this.

Thanks

**Comment by wisdomekpotu** [comment]
Hello thanks a lot guys for pointing out this....

I will update the article as soon as possible.

**Comment by wcomicho** [comment]
> Take my advice with some skepticism since I'm a python dev just dipping my toes into react + firebase, but this is what I had to do after the change above (in case you are stuck on the google signin):
> 
> * In `UserAuthContextProvider.js`, add these imports:
>   `import {signInWithPopup, GoogleAuthProvider } from "firebase/auth";`
>   -create a new function under the `UserAuthContextProvider` function
>   `function googleSignIn() { const googleProvider = new GoogleAuthProvider(); return signInWithPopup(auth, googleProvider); }`
> * add this new function to the return statement:
>   `<userAuthContext.Provider value={{ user, logIn, signUp, logOut, googleSignIn }} >`
> 
> Nothing extra seems to be needed to "sign UP" with google, initial login through google from a new user creates a user account automatically visible in the firebase console.
> 
> these docs were helpful: [https://firebase.google.com/docs/auth/web/google-signin#before_you_begin]
> 
> Good luck :)
> 
> and thank you @wisdomekpotu for the initial post. Incredibly helpful.

I will try this one out. Just started with Firebase, so need to keep learning for my new job. Thanks again.
