### ISSUE TITLE
Missing googleSignIn function on tutorial

### ISSUE THREAD

**Issue by SeuRonao** [wisdomekpotu/react18-firebasev9-auth#4]
Hello,
I followed your tutorial for authentication with google.
However I found out that the `googleSignIn` function is missing in the context part of the tutorial.

![image](https://user-images.githubusercontent.com/22750712/177201991-9f9acd2e-cc4e-450f-b4f8-f6d036aebee6.png)

In the end I was able to fully do authentication, by checking this repository code.
Thanks.

**Comment by wisdomekpotu** [comment]
Yes .....thank you

I will update that tutorial soon
